<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'remg_generator.entity_builder' shared service.

return $this->services['remg_generator.entity_builder'] = new \Remg\GeneratorBundle\Mapping\EntityBuilder();
