<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'remg_generator.entity_factory' shared service.

return $this->services['remg_generator.entity_factory'] = new \Remg\GeneratorBundle\Mapping\EntityFactory(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['remg_generator.bundle_manager']) ? $this->services['remg_generator.bundle_manager'] : $this->load('getRemgGenerator_BundleManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['remg_generator.classmetadata_factory']) ? $this->services['remg_generator.classmetadata_factory'] : $this->load('getRemgGenerator_ClassmetadataFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['remg_generator.entity_builder']) ? $this->services['remg_generator.entity_builder'] : $this->services['remg_generator.entity_builder'] = new \Remg\GeneratorBundle\Mapping\EntityBuilder()) && false ?: '_'});
