<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'remg_generator.bundle_manager' shared service.

return $this->services['remg_generator.bundle_manager'] = new \Remg\GeneratorBundle\Tools\BundleManager(${($_ = isset($this->services['remg_generator.kernel_bundles']) ? $this->services['remg_generator.kernel_bundles'] : $this->load('getRemgGenerator_KernelBundlesService.php')) && false ?: '_'});
