<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'remg_generator.entity_generator' shared service.

return $this->services['remg_generator.entity_generator'] = new \Remg\GeneratorBundle\Generator\EntityGenerator(${($_ = isset($this->services['remg_generator.classmetadata_factory']) ? $this->services['remg_generator.classmetadata_factory'] : $this->load('getRemgGenerator_ClassmetadataFactoryService.php')) && false ?: '_'}, $this->parameters['remg_generator.entity']);
