<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUza8ktx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUza8ktx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUza8ktx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUza8ktx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUza8ktx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uza8ktx',
    'container.build_id' => 'b592077e',
    'container.build_time' => 1526294607,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUza8ktx');
