<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Artikel extends \AppBundle\Entity\Artikel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'naam', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'omschrijving', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'technischeSpecificaties', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'inkoopprijs', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'minimaleVoorraad', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'aantalVoorraad', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'bestelserie', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'magazijnFk', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'alternatiefArtikelFk'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'naam', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'omschrijving', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'technischeSpecificaties', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'inkoopprijs', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'minimaleVoorraad', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'aantalVoorraad', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'bestelserie', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'magazijnFk', '' . "\0" . 'AppBundle\\Entity\\Artikel' . "\0" . 'alternatiefArtikelFk'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Artikel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNaam($naam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaam', [$naam]);

        return parent::setNaam($naam);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaam', []);

        return parent::getNaam();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmschrijving($omschrijving)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmschrijving', [$omschrijving]);

        return parent::setOmschrijving($omschrijving);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmschrijving()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmschrijving', []);

        return parent::getOmschrijving();
    }

    /**
     * {@inheritDoc}
     */
    public function setTechnischeSpecificaties($technischeSpecificaties)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTechnischeSpecificaties', [$technischeSpecificaties]);

        return parent::setTechnischeSpecificaties($technischeSpecificaties);
    }

    /**
     * {@inheritDoc}
     */
    public function getTechnischeSpecificaties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTechnischeSpecificaties', []);

        return parent::getTechnischeSpecificaties();
    }

    /**
     * {@inheritDoc}
     */
    public function setInkoopprijs($inkoopprijs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInkoopprijs', [$inkoopprijs]);

        return parent::setInkoopprijs($inkoopprijs);
    }

    /**
     * {@inheritDoc}
     */
    public function getInkoopprijs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInkoopprijs', []);

        return parent::getInkoopprijs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimaleVoorraad($minimaleVoorraad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimaleVoorraad', [$minimaleVoorraad]);

        return parent::setMinimaleVoorraad($minimaleVoorraad);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimaleVoorraad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimaleVoorraad', []);

        return parent::getMinimaleVoorraad();
    }

    /**
     * {@inheritDoc}
     */
    public function setAantalVoorraad($aantalVoorraad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAantalVoorraad', [$aantalVoorraad]);

        return parent::setAantalVoorraad($aantalVoorraad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAantalVoorraad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAantalVoorraad', []);

        return parent::getAantalVoorraad();
    }

    /**
     * {@inheritDoc}
     */
    public function setBestelserie($bestelserie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBestelserie', [$bestelserie]);

        return parent::setBestelserie($bestelserie);
    }

    /**
     * {@inheritDoc}
     */
    public function getBestelserie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBestelserie', []);

        return parent::getBestelserie();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagazijnFk(\AppBundle\Entity\Magazijn $magazijnFk = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagazijnFk', [$magazijnFk]);

        return parent::setMagazijnFk($magazijnFk);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagazijnFk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagazijnFk', []);

        return parent::getMagazijnFk();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlternatiefArtikelFk(\AppBundle\Entity\Artikel $alternatiefArtikelFk = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlternatiefArtikelFk', [$alternatiefArtikelFk]);

        return parent::setAlternatiefArtikelFk($alternatiefArtikelFk);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlternatiefArtikelFk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlternatiefArtikelFk', []);

        return parent::getAlternatiefArtikelFk();
    }

}
